export const appConfig = {
    "name": "Aluracord - LOTR",
    "theme": {
        "colors": {
            "primary": {
                "050": "#D3C79C",
                "100": "#CDBF8E",
                "200": "#C7B77F",
                "300": "#C1B071",
                "400": "#BBA863",
                "500": "#B4A055",
                "600": "#AA954B",
                "700": "#9C8944",
                "800": "#8E7D3E",
                "900": "#807038"
            },
            "neutrals": {
                "000": "#B4A055",
                "050": "#DD4048",
                "100": "#DA2F37",
                "200": "#BBA863",
                "300": "#C1B071",
                "400": "#AD1F26",
                "500": "#9C1C22",
                "600": "#8B181E",
                "700": "#79151A",
                "800": "#5c1014",
                "900": "#570F13",
                "999": "#460C0F"
            }
        }
    },
    "stickers": [
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_1.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_2.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_3.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_4.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_5.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_6.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_7.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_8.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_9.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_10.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_11.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_12.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_13.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_14.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_15.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_16.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_17.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_18.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_19.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_20.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_21.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_22.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_23.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_24.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_25.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_26.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_27.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_28.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_29.png",
        "https://www.alura.com.br/imersao-react-4/assets/figurinhas/Figurinha_30.png",
        "http://2.bp.blogspot.com/-d21tffsTIQo/U_H9QjC69gI/AAAAAAAAKqM/wnvOyUr6a_I/s1600/Pikachu%2B2.gif",
        "https://media1.giphy.com/media/BdghqxNFV4efm/200.gif",
        "https://c.tenor.com/TKpmh4WFEsAAAAAC/alura-gaveta-filmes.gif",
        "https://i.pinimg.com/originals/0b/1c/23/0b1c2307c83e1ebdeed72e41b9a058ad.gif",
        "https://c.tenor.com/VylWt5lyjBoAAAAC/omg-yes.gif",
        "https://i.pinimg.com/originals/96/34/c5/9634c520c9a3cd4e7f23190bb2c96500.gif"
    ]
}
